[package]
name = "ignition"
version = "1.0.0"
edition = "2024"
links = "ignition_sys"
license = "MIT"

[lib]
name = "ignition"
crate-type = ["lib"]
doctest = false
test = false

[dependencies]
thiserror = "1.0"

[build-dependencies]
thiserror = "1.0"

[features]
default = ["download-onnxruntime", "download-opencv"]
download-onnxruntime = []
download-opencv = []

