# Aliases for select target triplets (by parts)
alias:
  # Android
  aarch64-linux-android:
    architecture: arm64-v8a
    vendor:
    operating_system:
    environment:
  armv7-linux-androideabi:
    architecture: armeabi-v7a
    vendor:
    operating_system:
    environment:
  i686-linux-android:
    architecture: x86
    vendor:
    operating_system:
    environment:
  # iOS
  aarch64-apple-ios:
    architecture: arm64
    vendor:
    operating_system:
    environment:
  aarch64-apple-ios-sim:
    architecture: arm64
    vendor:
    operating_system:
    environment: simulator
  x86_64-apple-ios:
    architecture: x86_64
    vendor:
    operating_system:
    environment:
  # Darwin
  aarch64-apple-darwin:
    architecture: arm64
    vendor:
    operating_system:
    environment:
  # Linux
  aarch64-unknown-linux-gnu:
    architecture: arm64
    vendor:
    operating_system:
    environment: